### PR TITLE
Bugfix/cant push

### LINKED ISSUE #32: Error: Command failed: git push
Before we push to `master` or `develop` or whatever git branch, we have to make sure that it is up-to-date 💣 

Unfortunately this messed up our git history 😞 
Flow is as follows:

1. **Alice** makes a release, the script pulls `develop` and updates `develop` + `master` (**note:** it never pulled `master` - out of sync)
2. **Bob** makes the next release, the script pulls `develop` and updates `develop` + `master` (**note:** it never pulled `master` - out of sync!). NOW BOB has messed up the git history, with out of sync master

```sh
Error: Command failed: git push
To github.com:axa-ch/aletheia.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:axa-ch/aletheia.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #32

### CODE REVIEW

File: lib-release.js [hunk 1]
```diff
@@ -347,6 +347,7 @@ const confirmedRelease = (type, version) => {
     () => execaSeries([
       `npm publish ${version === BETA ? ' --tag beta' : ''}`,
       `git checkout ${TRUNK} --quiet`,
+      'git pull',
       `git merge --ff-only ${RELEASE_TMP}`,
```
Comment (AndyOGo) [inline lib-release.js]: Fast-Forward merge will only work, if we up-to-date!

File: lib-release.js [hunk 2]
```diff
@@ -362,6 +363,7 @@ const confirmedRelease = (type, version) => {
       ...releaseSteps,
       () => execaSeries([
         `git checkout ${MASTER_TRUNK} --quiet`,
+        'git pull',
         `git merge --no-ff ${DEVELOP_TRUNK}`,
         'git push',
```
Comment (AndyOGo) [inline lib-release.js]: non-forward pushes to `master` will be blocked

Comment (AndyOGo) [reply lib-release.js]: And out of sync merges cause hiccups

**Comment by AndyOGo** [comment]
@LucaMele 
We need this asap, because currently this script messes with git history if used by multiple users 😞 
So I merge without your review.
