### PR TITLE
should fix injected version issue

### LINKED ISSUE #10: injected version number is always one behind
We just had the use case to inject the `version` field of the `package.json` for testing and debugging purpose.
**But** it's always on behind, because the build:
1) runs `npm run build` (which has only access to the old version)
2) runs `npm verison ...` (here the version bump happens too late)

Code like this makes this issue obvious:

```js
import package from './package.json'

console.log(package.verison)
```

Or utilizing Babel's [`version-transform` plugin](https://www.npmjs.com/package/babel-plugin-version-transform).

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #10

### CODE REVIEW

File: lib-release.js [hunk 1]
```diff
@@ -297,28 +297,28 @@ const confirmedRelease = (type, version) => {
           Step 1 complete...
         `));
     }),
+    () => execaSeries([
+      type === UNSTABLE ? mapCommands[`bump-${version === BETA ? '' : `${version}-`}beta`] : mapCommands[`bump-${version}`],
```
Comment (AndyOGo) [inline lib-release.js]: @LucaMele 
Now the only possible issue I can think of is that if the `build` itself fails, we would have already a new version commited to `package.json` and a git tag would have been generated, which needs to be cleaned up upon error 🤔

Comment (LucaMele) [reply lib-release.js]: i guess yes..

Comment (AndyOGo) [reply lib-release.js]: Okay I just checked the docs, and we could [prevent git tags and commits](https://www.npmjs.com/package/npmversion#possible-options), by:
```sh
--nogit-commit
        No git commit

    --nogit-tag
        No git tag
```
