### PR TITLE
fix: should fix windows

### LINKED ISSUE #25: Windows: release still fails due to a commit error
image

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #25

### CODE REVIEW

File: lib-release.js [hunk 1]
```diff
@@ -326,7 +326,9 @@ const confirmedRelease = (type, version) => {
           Step 2 complete...
         `));
     }).catch((reason) => {
-      if (!~reason.stdout.indexOf('working tree clean')) {
```
Comment (AndyOGo) [inline lib-release.js]: @LucaMele 
@mjenny 
Seems that `stdout` isn't equally populated across platforms.
So I check for both `message` and `stdout`.

Still needs windows test.
